Eventbriteassignment/WebMvc/Controllers/EventController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebMvc.Services;
using WebMvc.ViewModels;

namespace WebMvc.Controllers
{
    public class EventController : Controller
    {
        private readonly IEventCatalogService _service;
        public EventController(IEventCatalogService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index(int? pageNumber, int? catalogFilter, int? placeFilter)
        {
            var itemsOnPage = 10;
            var events = await _service.GetEventCatalogItemsAsync(pageNumber ?? 0, itemsOnPage,
                catalogFilter, placeFilter);


            var vm = new EventIndexViewModel
            {
                Categories = await _service.GetCategoriesAsync(),
                Places = await _service.GetPlacesAsync(),
                EventCatalogItems = events.Data,
                PaginationInfo = new PaginationInfo
                {
                    ActualPage = events.PageIndex,
                    TotalItems = events.Count,
                    ItemsPerPage = events.PageSize,
                    TotalPages = (int)Math.Ceiling((decimal)events.Count / itemsOnPage)
                },
                CategoryFilter = catalogFilter,
                PlaceFilter = placeFilter
            };

            return View(vm);
        }


        [Authorize]
        public IActionResult About()
        {
            return View();
        }

       
       
    }
}

Eventbriteassignment/WebMvc/Controllers/TicketOrderController.cs
using Microsoft.AspNetCore.Mvc;
using Polly.CircuitBreaker;
using Stripe;
using WebMvc.Models;
using WebMvc.Services;

namespace WebMvc.Controllers
{
    //[Authorize]
    public class TicketOrderController : Controller
    {
        private readonly ITicketOrderService _orderSvc;
        //private readonly ILogger<TicketOrderController> _logger;
        private readonly IConfiguration _config;
        //private readonly IIdentityService<ApplicationUser> _identitySvc;


        public TicketOrderController(IConfiguration config,
            ILogger<TicketOrderController> logger,
            ITicketOrderService orderSvc
            //IIdentityService<ApplicationUser> identitySvc)
            )
        {
            _orderSvc = orderSvc;
            //_logger = logger;
            _config = config;
            //_identitySvc = identitySvc;
        }


        [HttpPost]
        public async Task<IActionResult> Create(TicketOrder fromEvent)
        {
            ViewBag.StripePublishableKey = _config["StripePublicKey"];
            //return RedirectToAction("Complete", new { id = fromEvent.OrderId, userName = "maddieijams@gmail.com" });

            var newOrder = new TicketOrder
            {
                OrderDate = DateTime.Now,
                OrderId = new Random().Next(),
                OrderStatus = OrderStatus.Preparing,
                OrderTotal = 20,
                FirstName = "",
                LastName = "",
                Address = "",
                BuyerId = "llddds",
                PaymentAuthCode = "80ljl090",
                TicketPrice = fromEvent.TicketPrice,
                EventName = fromEvent.EventName,
                Quantity = fromEvent.Quantity,

            };
            //return View(newOrder);


            //if (ModelState.IsValid)
            //{
            //var user = _identitySvc.Get(HttpContext.User);

            TicketOrder order = newOrder;

            //order.UserName = user.Email;
            //order.BuyerId = "";

            var options = new RequestOptions
            {
                ApiKey = _config["StripePrivateKey"]
            };
            var chargeOptions = new ChargeCreateOptions
            {
                //required
                Amount = (int)(order.OrderTotal * 100),
                Currency = "usd",
                Source = order.StripeToken,
                Customer = "cus_AFGbOSiITuJVDs",

            };

            var chargeService = new ChargeService();

            Charge stripeCharge = null;
            try
            {
                stripeCharge = chargeService.Create(chargeOptions, options);
                //_logger.LogDebug("Stripe charge object creation" + stripeCharge.StripeResponse.ToString());
            }
            catch (StripeException stripeException)
            {
                //_logger.LogDebug("Stripe exception " + stripeException.Message);
                ModelState.AddModelError(string.Empty, stripeException.Message);
                return View(newOrder);
            }

            try
            {
                if (stripeCharge.Id != null)
                {
                    //_logger.LogDebug("TransferID :" + stripeCharge.Id);
                    order.PaymentAuthCode = stripeCharge.Id;

                    //_logger.LogDebug("User {userName} started order processing", user.UserName);
                    int orderId = await _orderSvc.CreateTicketOrder(order);
                    //_logger.LogDebug("User {userName} finished order processing  of {orderId}.", order.UserName, order.OrderId);

                    return RedirectToAction("Complete", new { id = orderId, userName = "maddieijams@gmail.com" });
                }
                else
                {
                    ViewData["message"] = "Payment cannot be processed, try again";
                    return View(newOrder);
                }
            }
            catch (BrokenCircuitException)
            {
                ModelState.AddModelError("Error", "It was not possible to create a new order, please try later on. (Business Msg Due to Circuit-Breaker)");
                return View(newOrder);
            }
            //}
            //else
            //{
            //return View(newOrder);
            //}
        }

        public IActionResult Complete(int id, string userName = "maddieijams@gmail.com")
        {

            //_logger.LogInformation("User {userName} completed checkout on order {orderId}.", userName, id);
            return View(id);

        }
    }
}

//namespace WebMvc.Controllers
//{
//    //[Authorize]
//    public class TicketOrderController : Controller
//    {
//        private readonly ITicketOrderService _orderSvc;
//        //private readonly IIdentityService<ApplicationUser> _identitySvc;
//        private readonly ILogger<TicketOrderController> _logger;
//        private readonly IConfiguration _config;


//        public TicketOrderController(IConfiguration config,
//            ILogger<TicketOrderController> logger,
//            ITicketOrderService orderSvc
//            //IIdentityService<ApplicationUser> identitySvc)
//            )
//        {
//            //_identitySvc = identitySvc;
//            _orderSvc = orderSvc;
//            _logger = logger;
//            _config = config;
//        }

//        public IActionResult Create()
//        {
//            //var user = _identitySvc.Get(HttpContext.User);
//            ViewBag.StripePublishableKey = _config["StripePublicKey"];
//            var order = new TicketOrder
//            {
//                OrderDate = DateTime.Now,
//                OrderId = 987,
//                OrderStatus = OrderStatus.Preparing,
//                OrderTotal = 20,
//                FirstName = "",
//                LastName = "",
//                Address = "",
//                BuyerId = "",
//                PaymentAuthCode = "",
//                TicketPrice = 20,
//                EventName = ""
//            };
//            return View(order);
//        }

//        [HttpPost]
//        public async Task<IActionResult> Create(TicketOrder frmOrder)
//        {

//            if (ModelState.IsValid)
//            {
//                //var user = _identitySvc.Get(HttpContext.User);

//                TicketOrder order = frmOrder;

//                //order.UserName = user.Email;
//                order.BuyerId = "";

//                var options = new RequestOptions
//                {
//                    ApiKey = _config["StripePrivateKey"]
//                };
//                var chargeOptions = new ChargeCreateOptions()

//                {
//                    //required
//                    Amount = (int)(order.OrderTotal * 100),
//                    Currency = "usd",
//                    Source = order.StripeToken,
//                    //optional
//                    Description = string.Format("Order Payment {0}", "fake"),
//                    ReceiptEmail = "maddieijams@gmail.com",

//                };

//                var chargeService = new ChargeService();



//                Charge stripeCharge = null;
//                try
//                {
//                    stripeCharge = chargeService.Create(chargeOptions, options);
//                    _logger.LogDebug("Stripe charge object creation" + stripeCharge.StripeResponse.ToString());
//                }
//                catch (StripeException stripeException)
//                {
//                    _logger.LogDebug("Stripe exception " + stripeException.Message);
//                    ModelState.AddModelError(string.Empty, stripeException.Message);
//                    return View(frmOrder);
//                }


//                try
//                {

//                    if (stripeCharge.Id != null)
//                    {
//                        //_logger.LogDebug("TransferID :" + stripeCharge.Id);
//                        order.PaymentAuthCode = stripeCharge.Id;

//                        //_logger.LogDebug("User {userName} started order processing", user.UserName);
//                        int orderId = await _orderSvc.CreateTicketOrder(order);
//                        //_logger.LogDebug("User {userName} finished order processing  of {orderId}.", order.UserName, order.OrderId);

//                        //await _cartSvc.ClearCart(user);
//                        return RedirectToAction("Complete", new { id = orderId, userName = "maddieijams@gmail.com" });
//                    }

//                    else
//                    {
//                        ViewData["message"] = "Payment cannot be processed, try again";
//                        return View(frmOrder);
//                    }

//                }
//                catch (BrokenCircuitException)
//                {
//                    ModelState.AddModelError("Error", "It was not possible to create a new order, please try later on. (Business Msg Due to Circuit-Breaker)");
//                    return View(frmOrder);
//                }
//            }
//            else
//            {
//                return View(frmOrder);
//            }
//        }

//        public IActionResult Complete(int id, string userName = "maddieijams@gmail.com")
//        {

//            _logger.LogInformation("User {userName} completed checkout on order {orderId}.", userName, id);
//            return View(id);

//        }
//    }
//}

Eventbriteassignment/WebMvc/Views/Event/About - Copy.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@using Microsoft.AspNetCore.Authentication;
<h2>TESt</h2>

Eventbriteassignment/WebMvc/Views/Event/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@using Microsoft.AspNetCore.Authentication;
<h2>Access Token</h2>
<dl>
    @foreach (var claim in User.Claims)
    {
        <dt>@claim.Type</dt>
        <dd>@claim.Value</dd>

    }
    <dt>access token</dt>
    <dd>@await ViewContext.HttpContext.GetTokenAsync("access_token")</dd>
    <dt>refresh token</dt>
    <dd>@await ViewContext.HttpContext.GetTokenAsync("refresh_token")</dd>
</dl>

Eventbriteassignment/WebMvc/Views/Event/Contact.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div>
    <p>
           Test
    </p>
 
</div>

Eventbriteassignment/WebMvc/Views/Event/Inde_oldx.cshtml
@{
    ViewData["Title"] = "Events";
    @model WebMvc.ViewModels.EventIndexViewModel
}
@*<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner.png" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Incredible Engagement Rings.
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner-2.png" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Diamond Engagement Rings are a thing!
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner-3.png" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Engagement rings are epitome of luxury.
                </p>
            </div>
        </div>

    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>*@

<section class="esh-catalog-filters">
    <div class="container">
        <form asp-action="Index" asp-controller="Catalog" method="post">
            <label class="esh-catalog-label" data-title="brand">
                <select asp-for="@Model.CategoryFilter" asp-items="@Model.Categories" class="esh-catalog-filter"></select>
            </label>
            <label class="esh-catalog-label" data-title="type">
                <select asp-for="@Model.PlaceFilter" asp-items="@Model.Places" class="esh-catalog-filter"></select>
            </label>
            <input class="esh-catalog-send" type="image" src="~/images/arrow-right.svg" />
        </form>
    </div>
</section>
<div class="container">
    @if (Model.EventCatalogItems.Count() > 0)
    {
        @Html.Partial("_pagination", Model.PaginationInfo)

        <div class="esh-catalog-items row">
            @foreach (var catalogItem in Model.EventCatalogItems)
            {
                <div class="esh-catalog-item col-md-4">
                    @Html.Partial("_event", catalogItem)
                </div>
            }
        </div>

        @Html.Partial("_pagination", Model.PaginationInfo)
    }
    else
    {
        <div class="esh-catalog-items row">
            THERE ARE NO RESULTS THAT MATCH YOUR SEARCH
        </div>
    }
</div>

Eventbriteassignment/WebMvc/Views/Event/Index.cshtml
@{
    ViewData["Title"] = "Events";
    @model WebMvc.ViewModels.EventIndexViewModel
}
@*<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner.png" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Incredible Engagement Rings.
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner-2.png" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Diamond Engagement Rings are a thing!
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner-3.png" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Engagement rings are epitome of luxury.
                </p>
            </div>
        </div>

    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>*@

<section class="esh-catalog-filters">
    <div class="container">
        <form asp-action="Index" asp-controller="Event" method="post">
            <label class="esh-catalog-label" data-title="category">
                <select asp-for="@Model.CategoryFilter" asp-items="@Model.Categories" class="esh-catalog-filter"></select>
            </label>
            <label class="esh-catalog-label" data-title="place">
                <select asp-for="@Model.PlaceFilter" asp-items="@Model.Places" class="esh-catalog-filter"></select>
            </label>
            <input class="esh-catalog-send" type="image" src="~/images/arrow-right.svg" />
        </form>
    </div>
</section>
<div class="container">
    @if (Model.EventCatalogItems.Count() > 0)
    {
        @Html.Partial("_pagination", Model.PaginationInfo)

        <div class="esh-catalog-items row">
            @foreach (var catalogItem in Model.EventCatalogItems)
            {
                <div class="esh-catalog-item col-md-4">
                    @Html.Partial("_event", catalogItem)
                </div>
            }
        </div>

        @Html.Partial("_pagination", Model.PaginationInfo)
    }
    else
    {
        <div class="esh-catalog-items row">
            THERE ARE NO RESULTS THAT MATCH YOUR SEARCH
        </div>
    }
</div>

Eventbriteassignment/WebMvc/Views/Event/_event.cshtml
@model WebMvc.Models.EventCatalogItem

@*<div>
    <img class="esh-catalog-thumbnail" src="@Model.PictureURL" />
    <a asp-action="Index" asp-controller="TicketOrder" class="btn btn-primary">Buy tickets</a>
    </div>*@
<form asp-controller="TicketOrder" asp-action="Create" >
     <img class="esh-catalog-thumbnail" src="@Model.PictureURL" />
    <div class="esh-catalog-name">
        <span>@Model.Name</span>
    </div>
    <div class="esh-catalog-price">
        <span>@Model.TicketPrice.ToString("N2")</span>
    </div>
     <div class="form-group grid-flex flex-row">
                        <label  class="">Quantity</label>
                        <input asp-for="@Model.TicketQuantity" class="form-control form-input" type="text" name="ticketQuantity" />
                    </div>
    <input class="esh-catalog-button" type="submit" value="Buy Tickets" />

    <input type="hidden" asp-for="@Model.Category" name="category" />
    <input type="hidden" asp-for="@Model.EventCategoryId" name="eventCategoryId" />
    <input type="hidden" asp-for="@Model.Place" name="place" />
    <input type="hidden" asp-for="@Model.EventPlaceId" name="eventPlaceId" />
    <input type="hidden" asp-for="@Model.Description" name="description" />
    <input type="hidden" asp-for="@Model.Id" name="id" />
    <input type="hidden" asp-for="@Model.Name" name="name" /> @*need*@
    @*TODO: this may need to be pictureUrl*@
    <input type="hidden" asp-for="@Model.PictureURL" name="pictureURL" />
    <input type="hidden" asp-for="@Model.TicketPrice" name="ticketPrice" /> @*need*@
</form>

Eventbriteassignment/WebMvc/Views/Event/_pagination.cshtml
@model WebMvc.ViewModels.PaginationInfo

<div class="esh-pager">
    <div class="container">
        <article class="esh-pager-wrapper row">
            <nav>
                <a class="esh-pager-item esh-pager-item--navigable @Model.Previous"
                   id="Previous"
                   asp-controller="Event"
                   asp-action="Index"
                   asp-route-page="@(Model.ActualPage -1)"
                   aria-label="Previous">
                    Previous
                </a>

                <span class="esh-pager-item">
                    Showing @Model.ItemsPerPage of @Model.TotalItems products - Page @(Model.ActualPage + 1) - @Model.TotalPages
                </span>

                <a class="esh-pager-item esh-pager-item--navigable @Model.Next"
                   id="Next"
                   asp-controller="Event"
                   asp-action="Index"
                   asp-route-page="@(Model.ActualPage + 1)"
                   aria-label="Next">
                    Next
                </a>
            </nav>
        </article>
    </div>
</div>